name: mca
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  intl:

  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  # get_it: ^8.0.3
  gap: ^3.0.1
  go_router: ^14.8.0

  logs:
     git:
       url: https://github.com/quochoang228/logs.git
       ref: main
  il:
     git:
       url: https://github.com/quochoang228/il.git
       ref: main
  ag:
     git:
       url: https://github.com/quochoang228/ag.git
       ref: main
  cdn:
     git:
       url: https://github.com/quochoang228/cdn.git
       ref: main
  ds:
     git:
       url: https://github.com/quochoang228/ds.git
       ref: main
  di:
    git:
      url: https://github.com/quochoang228/di.git
      ref: main
  router:
    git:
      url: https://github.com/quochoang228/router.git
      ref: main
  utils:
    git:
      url: https://github.com/quochoang228/utils.git
      ref: main

  storage:
    git:
      url: https://github.com/quochoang228/storage.git
      path: storage
      ref: main

  persistent_storage:
    git:
      url: https://github.com/quochoang228/storage.git
      path: persistent_storage
      ref: main

  auth:
    git:
      url: https://github.com/quochoang228/auth.git
      ref: main
    
  ioc_contact_request:
    path: packages/ioc_contact_request

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
