name: ioc_contact_request
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  # get_it: ^8.0.3
  gap: ^3.0.1
  go_router: ^14.8.0
  nb_utils: ^7.1.3
  intl: ^0.19.0
  flutter_form_builder: ^10.0.1

  logs:
    git:
      url: https://github.com/quochoang228/logs.git
      ref: main

  auth:
    git:
      url: https://github.com/quochoang228/auth.git
      ref: main

  ds:
    git:
      url: https://github.com/quochoang228/ds.git
      ref: main

  ag:
    git:
      url: https://github.com/quochoang228/ag.git
      ref: main

  di:
    git:
      url: https://github.com/quochoang228/di.git
      ref: main

  router:
    git:
      url: https://github.com/quochoang228/router.git
      ref: main

  cdn:
    git:
      url: https://github.com/quochoang228/cdn.git
      ref: main
    
  utils:
    git:
      url: https://github.com/quochoang228/utils.git
      ref: main

  storage:
    git:
      url: https://github.com/quochoang228/storage.git
      path: storage
      ref: main

  persistent_storage:
    git:
      url: https://github.com/quochoang228/storage.git
      path: persistent_storage
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
